import { useEffect, useState } from 'react';
import { MapPin, X, Clock, ShieldCheck } from 'lucide-react';
import { cobradorService, collectorPortalService } from '../../services/cobradorService';

export default function LocationSessionModal({ collector, onClose }) {
  const [assignments, setAssignments] = useState([]);
  const [selected, setSelected] = useState('');
  const [minutes, setMinutes] = useState(30);
  const [loading, setLoading] = useState(true);
  const [starting, setStarting] = useState(false);
  const [message, setMessage] = useState('');
  useEffect(() => { collectorPortalService.getAssignments(collector.id).then(setAssignments).catch(() => setMessage('No se pudieron cargar las asignaciones.')).finally(() => setLoading(false)); }, [collector.id]);
  const start = async () => { if (!selected) return; setStarting(true); setMessage(''); try { const result = await cobradorService.startLocationSession(selected, Number(minutes)); setMessage(`Sesión iniciada hasta ${new Date(result.expiresAt).toLocaleTimeString()}. El cliente debe tener el consentimiento vigente y el permiso de ubicación activo.`); } catch (error) { setMessage(error.response?.data?.message || 'No se pudo iniciar la sesión.'); } finally { setStarting(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-navy-950/60 p-4" onClick={onClose}><div className="w-full max-w-lg rounded-16 bg-white shadow-card-lg" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-surface-border p-6"><div><div className="mb-2 flex items-center gap-2 text-accent-600"><MapPin size={19} /><span className="text-xs font-bold uppercase tracking-wider">Ubicación temporal</span></div><h2 className="text-lg font-bold text-navy-500">Iniciar sesión de visita</h2><p className="text-sm text-slate-400">Cobrador: {collector.nombre}</p></div><button type="button" onClick={onClose} className="rounded-8 p-2 text-slate-400 hover:bg-surface-hover" aria-label="Cerrar"><X size={19} /></button></div><div className="space-y-5 p-6"><div className="flex gap-3 rounded-8 border border-warning-200 bg-warning-50 p-3 text-xs leading-5 text-warning-800"><ShieldCheck size={17} className="mt-0.5 shrink-0" />Solo se mostrará la última ubicación durante la sesión activa. La sesión expira automáticamente y cada consulta queda auditada.</div>{loading ? <p className="text-sm text-slate-400">Cargando préstamos asignados...</p> : <label className="block"><span className="mb-1 block text-xs font-semibold text-slate-500">Préstamo y cliente</span><select value={selected} onChange={(event) => setSelected(event.target.value)} className="w-full rounded-8 border border-surface-border bg-white px-3 py-2.5 text-sm"><option value="">Selecciona una asignación</option>{assignments.map((assignment) => <option key={assignment.id} value={assignment.id}>{assignment.clienteNombre} · {String(assignment.loanId).slice(0, 8)} · saldo {Number(assignment.saldoPendiente || 0).toLocaleString()}</option>)}</select></label>}<label className="block"><span className="mb-1 flex items-center gap-1 text-xs font-semibold text-slate-500"><Clock size={13} />Duración</span><select value={minutes} onChange={(event) => setMinutes(event.target.value)} className="w-full rounded-8 border border-surface-border bg-white px-3 py-2.5 text-sm"><option value={15}>15 minutos</option><option value={30}>30 minutos</option><option value={45}>45 minutos</option><option value={60}>60 minutos</option></select></label>{message && <p className="rounded-8 bg-surface-canvas p-3 text-sm text-slate-600">{message}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-8 px-4 py-2 text-sm text-slate-500 hover:bg-surface-hover">Cerrar</button><button type="button" onClick={start} disabled={!selected || starting || loading} className="flex items-center gap-2 rounded-8 bg-gradient-to-r from-accent-500 to-accent-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><MapPin size={15} />{starting ? 'Iniciando...' : 'Iniciar sesión'}</button></div></div></div></div>;
}
