import { useEffect, useMemo, useState } from 'react';
import { BookOpen, ChevronLeft, ChevronRight, X } from 'lucide-react';

const guides = {
  '/admin': { title: 'Panel principal', intro: 'Una lectura rápida de esta vista.', steps: [['Resumen', 'Aquí ves el estado general de tu cartera y las cifras que requieren atención.'], ['Acciones rápidas', 'Usa los accesos destacados para registrar clientes, préstamos o revisar solicitudes.'], ['Actividad', 'Consulta los movimientos recientes para mantener el control del día.']] },
  '/admin/clientes': { title: 'Clientes', intro: 'Administra tus expedientes desde un solo lugar.', steps: [['Buscar', 'Filtra por nombre, teléfono o documento para encontrar un expediente.'], ['Nuevo cliente', 'Crea el perfil con los datos necesarios antes de registrar un préstamo.'], ['Expediente', 'Abre un cliente para consultar sus préstamos, pagos y documentos.']] },
  '/admin/prestamos': { title: 'Préstamos', intro: 'Consulta y controla toda tu cartera.', steps: [['Filtros', 'Usa estado, fecha y moneda para concentrarte en una parte de la cartera.'], ['Detalle', 'Abre un préstamo para revisar cuotas, saldo, pagos y amortización.'], ['Seguimiento', 'Mantén cada pago actualizado para que el saldo siempre sea confiable.']] },
  '/admin/nuevo-prestamo': { title: 'Nuevo préstamo', intro: 'Registra una operación con sus condiciones reales.', steps: [['Cliente y moneda', 'Selecciona el cliente y la divisa de esta operación.'], ['Condiciones', 'Define monto, tasa, plazo y frecuencia de pago.'], ['Confirmar', 'Revisa la tabla de cuotas antes de guardar el desembolso.']] },
  '/admin/solicitudes': { title: 'Solicitudes', intro: 'Revisa las solicitudes antes de decidir.', steps: [['Bandeja', 'Cada tarjeta representa una solicitud pendiente o procesada.'], ['Evaluar', 'Consulta identidad, referencias, garantías y capacidad de pago.'], ['Decidir', 'Aprueba o rechaza dejando el estado de la solicitud actualizado.']] },
  '/admin/cobradores': { title: 'Cobradores', intro: 'Organiza el trabajo de campo.', steps: [['Equipo', 'Consulta quién está activo y qué zona atiende.'], ['Asignar', 'Distribuye clientes y visitas para ordenar el recorrido.'], ['Resultado', 'Revisa pagos y evidencias reportadas por cada cobrador.']] },
  '/admin/mora': { title: 'Mora y cobranza', intro: 'Convierte atrasos en acciones concretas.', steps: [['Prioridad', 'Ordena los casos por días de atraso y saldo pendiente.'], ['Contexto', 'Abre cada registro para revisar historial y último contacto.'], ['Acción', 'Coordina una visita o registra el acuerdo de pago correspondiente.']] },
  '/admin/configuracion': { title: 'Configuración de divisas', intro: 'Define cómo opera tu empresa.', steps: [['Habilitar', 'Activa las monedas que realmente manejarás.'], ['Capital', 'Escribe el capital inicial de cada divisa antes de guardar.'], ['Guardar', 'La configuración separa los saldos para no mezclar operaciones.']] },
};

function getGuide(pathname) { return guides[pathname] || { title: 'Esta vista', intro: 'Aprende lo esencial de esta pantalla.', steps: [['Ubicación', 'Esta pantalla reúne las herramientas de una tarea específica.'], ['Acción', 'Lee los títulos y usa los botones principales para avanzar.'], ['Revisión', 'Confirma los datos antes de guardar cualquier cambio.']] }; }

export default function ProductGuide() {
  const pathname = window.location.pathname.replace(/\/$/, '') || '/admin';
  const guide = useMemo(() => getGuide(pathname), [pathname]);
  const storageKey = `prestamoplus-guide:${pathname}`;
  const [open, setOpen] = useState(() => localStorage.getItem(storageKey) !== 'done');
  const [step, setStep] = useState(0);
  useEffect(() => { setStep(0); setOpen(localStorage.getItem(storageKey) !== 'done'); }, [storageKey]);
  const close = () => { localStorage.setItem(storageKey, 'done'); setOpen(false); };
  return <><button type="button" onClick={() => { setStep(0); setOpen(true); }} className="fixed bottom-5 right-5 z-30 inline-flex items-center gap-2 rounded-full bg-navy-900 px-4 py-3 text-xs font-bold text-white shadow-card-lg transition hover:-translate-y-0.5" aria-label={`Abrir guía de ${guide.title}`}><BookOpen size={16} /> Guía</button>{open && <div className="fixed inset-0 z-40 flex items-end justify-center bg-navy-900/35 p-4 sm:items-center"><section role="dialog" aria-modal="true" aria-labelledby="guide-title" className="w-full max-w-md rounded-16 border border-surface-border bg-white p-6 shadow-card-lg"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-accent-600">Guía independiente · {step + 1}/{guide.steps.length}</p><h2 id="guide-title" className="mt-2 font-display text-2xl font-extrabold text-navy-800">{guide.title}</h2><p className="mt-1 text-sm text-slate-500">{guide.intro}</p></div><button type="button" onClick={close} className="rounded-full p-2 text-slate-400 hover:bg-slate-100" aria-label="Cerrar guía"><X size={18} /></button></div><div className="mt-4 rounded-12 border border-accent-100 bg-accent-50/40 p-4"><p className="text-xs font-bold uppercase tracking-wider text-accent-700">¿Qué hace PréstamoPlus?</p><p className="mt-2 text-sm leading-6 text-navy-700">Es el espacio donde organizas clientes, préstamos, cuotas, pagos, cobranza y saldos por divisa, con una historia clara de cada operación.</p></div><div className="mt-4 rounded-12 bg-surface-canvas p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{guide.steps[step][0]}</p><p className="mt-2 text-sm leading-6 text-navy-700">{guide.steps[step][1]}</p></div><div className="mt-5 flex items-center justify-between"><button type="button" onClick={close} className="text-xs font-semibold text-slate-500 hover:text-navy-800">Saltar guía</button><div className="flex gap-2"><button type="button" disabled={step === 0} onClick={() => setStep((value) => value - 1)} className="rounded-8 border border-surface-border p-2 text-navy-700 disabled:opacity-30" aria-label="Paso anterior"><ChevronLeft size={17} /></button>{step === guide.steps.length - 1 ? <button type="button" onClick={close} className="rounded-8 bg-accent-600 px-4 py-2 text-xs font-bold text-white">Listo</button> : <button type="button" onClick={() => setStep((value) => value + 1)} className="inline-flex items-center gap-1 rounded-8 bg-navy-900 px-4 py-2 text-xs font-bold text-white">Siguiente <ChevronRight size={15} /></button>}</div></div></section></div>}</>;
}
