import { useEffect, useState } from 'react';
import { Coins, Save } from 'lucide-react';
import api from '../../services/api';
import { CURRENCY_CATALOG } from '../../data/currencies';

export default function Configuracion() {
  const [config, setConfig] = useState(null);
  const [selected, setSelected] = useState([]);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  useEffect(() => { api.get('/api/tenant/config').then(({ data }) => { setConfig(data); setSelected(data.monedasHabilitadas || ['DOP']); }).catch(() => setMessage('No se pudo cargar la configuración.')); }, []);
  const save = async () => { setSaving(true); setMessage(''); try { const { data } = await api.put('/api/tenant/config', { nombre: config.nombre, logoUrl: config.logoUrl, email: config.email, telefono: config.telefono, monedasHabilitadas: selected }); setConfig(data); setSelected(data.monedasHabilitadas || selected); setMessage('Divisas guardadas correctamente.'); } catch (error) { setMessage(error.response?.data?.message || 'No se pudo guardar.'); } finally { setSaving(false); } };
  return <div><div className="mb-8"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-accent-600">Configuración operativa</p><h1 className="mt-1 font-display text-3xl font-extrabold text-navy-800">Divisas</h1><p className="text-sm text-slate-500">Agrega nuevas monedas después del registro sin mezclar saldos entre ellas.</p></div><section className="max-w-4xl rounded-12 border border-surface-border bg-white p-6 shadow-card"><div className="flex items-start gap-3"><div className="rounded-8 bg-accent-50 p-2 text-accent-600"><Coins size={20} /></div><div><h2 className="font-bold text-navy-500">Monedas habilitadas</h2><p className="text-sm text-slate-400">La moneda predeterminada debe permanecer seleccionada. Los préstamos nuevos usarán la moneda elegida en su solicitud.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{CURRENCY_CATALOG.map((currency) => { const checked = selected.includes(currency.code); return <label key={currency.code} className={`flex cursor-pointer items-center gap-3 rounded-8 border p-4 ${checked ? 'border-accent-300 bg-accent-50/50' : 'border-surface-border'}`}><input type="checkbox" checked={checked} onChange={() => setSelected((current) => checked ? current.filter((code) => code !== currency.code) : [...current, currency.code])} className="h-4 w-4" /><span className="text-xl">{currency.flag}</span><span><b className="text-sm text-navy-500">{currency.code}</b><span className="block text-xs text-slate-400">{currency.name}</span></span></label>; })}</div>{message && <p className="mt-4 text-sm text-accent-700">{message}</p>}<button type="button" disabled={saving || !selected.length || !config} onClick={save} className="mt-6 flex items-center gap-2 rounded-8 bg-gradient-to-r from-accent-500 to-accent-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={16} />{saving ? 'Guardando...' : 'Guardar divisas'}</button></section></div>;
}
